config/routes.rb
Rails.application.routes.draw do
  root 'percorsos#index'
  resources :percorsos do
    resources :partecipantis, only: [:create, :destroy]
  end

  get '/auth/google/callback', to:  "sessions#create"

  delete '/logout', to: 'sessions#destroy'

  resources :percorsos do
    patch :send_message, on: :member
    patch :aggiorna_photo, on: :member
  end

end

app/models/percorso.rb
class Percorso < ActiveRecord::Base
end

app/controllers/percorsos_controller.rb
require 'httparty'
require 'bunny'
class PercorsosController < ApplicationController
  before_action :set_percorso, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, except: [:index, :show]

  # GET /percorsos
  # GET /percorsos.json
  def index
    partenza = params[:partenza]
    destinazione = params[:destinazione]
    data = params[:data]
    @percorsos = Percorso.all
    @percorsos = @percorsos.where("lower(partenza) = ?", partenza.downcase) if ! partenza.nil? && ! partenza.empty?
    @percorsos = @percorsos.where("lower(destinazione) = ?", destinazione.downcase) if !destinazione.nil? && ! destinazione.empty?
    @percorsos = @percorsos.where("lower(data) = ?", data.downcase) if !data.nil? && ! data.empty?
  end

  # GET /percorsos/1
  # GET /percorsos/1.json
  def show
    utente = User.find_by(uid: @percorso.utref)
    @utente = utente.name
    @fotoC = utente.image_url
    @partecipanti = Partecipanti.all
    @partecipanti = @partecipanti.where("percorso = ?", @percorso)
    @partecipanteInfo = []
    @partecipanti.each do |p|
      user = User.find_by(uid: p.utente)
      foto = user.image_url
      name = user.name
      @partecipanteInfo.push([foto, name, user.uid])
    end
    @messages = []
    if current_user
      @isPartecipante = @partecipanti.exists?(utente: current_user.uid)
      @partecipante = @partecipanti.find_by(utente: current_user.uid)
      if @isPartecipante || current_user.uid.to_s == @percorso.utref.to_s
        conn = Bunny.new
        conn.start
        ch  = conn.create_channel
        x   = ch.topic("#{@percorso.id}")
        q   = ch.queue("#{@percorso.id}#{current_user.uid}")
        if @isPartecipante
          q.bind(x, :routing_key => "all")
          q.bind(x, :routing_key => "#{current_user.uid}")
        else
          q.bind(x, :routing_key => "*.#{current_user.uid}")
        end

        begin
          q.subscribe(:block => false) do |delivery_info, properties, body|
            if @isPartecipante
              id = delivery_info.routing_key
              user = User.find_by(uid: @percorso.utref)
              foto = user.image_url
              name = user.name
            else
              id = delivery_info.routing_key.split(".").first
              user = User.find_by(uid: id)
              foto = user.image_url
              name = user.name
            end
            @messages.push([id, foto, name, body])
          end
          ch.close
          conn.close
        rescue Interrupt => _
          ch.close
          conn.close
        end
      end
    end

  end

  # GET /percorsos/new
  def new
    @percorso = Percorso.new
  end

  # GET /percorsos/1/edit
  def edit
  end

  # POST /percorsos
  # POST /percorsos.json
  def create
    @percorso = Percorso.new(percorso_params)
    @percorso.utref = current_user.uid
    a = @percorso.partenza
    b = @percorso.destinazione

    doc = HTTParty.get('https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins='+
    a+',italia&destinations='+b+',italia&key=AIzaSyBvf51KQC6u-v6nVflhxbD0xbC1PSJEdpM')
    d=JSON.parse(doc.body)['rows'][0]['elements'][0]['duration']['value']

    @percorso.durata=d
    respond_to do |format|
      if @percorso.save
        conn = Bunny.new
        conn.start
        ch = conn.create_channel
        x = ch.topic("#{@percorso.id}")
        queue = ch.queue("#{@percorso.id}#{current_user.uid}")
        topic = "*." + current_user.uid
        queue.bind(x, :routing_key => topic)
        ch.close
        conn.close

        format.html { redirect_to @percorso, notice: 'Percorso was successfully created.' }
        format.json { render :show, status: :created, location: @percorso }
      else
        format.html { render :new }
        format.json { render json: @percorso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /percorsos/1
  # PATCH/PUT /percorsos/1.json
  def update
    respond_to do |format|
      if @percorso.update(percorso_params)
        format.html { redirect_to @percorso, notice: 'Percorso was successfully updated.' }
        format.json { render :show, status: :ok, location: @percorso }
      else
        format.html { render :edit }
        format.json { render json: @percorso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /percorsos/1
  # DELETE /percorsos/1.json
  def destroy
    @percorso = Percorso.find(params[:id])
    @percorso.destroy

    redirect_to root_path
  end

  def send_message
    @percorso = Percorso.find(params[:id])
    text = params[:message][:text]
    destinatario = params[:destinatario][:id]
    conn = Bunny.new
    conn.start
    ch = conn.create_channel
    x = ch.topic("#{@percorso.id}")
    x.publish(text, :routing_key => destinatario)
    ch.close
    conn.close
  end

  def aggiorna_photo
    @percorso = Percorso.find(params[:id])
    @percorso.image = params[:patch][:photo]
    @percorso.save
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_percorso
      @percorso = Percorso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def percorso_params
      params.require(:percorso).permit(:data, :ora, :partenza, :destinazione, :durata, :utref)
    end

    def require_login
      unless current_user
        redirect_to '/auth/google/'
      end
    end
end

app/helpers/percorsos_helper.rb
module PercorsosHelper
end

app/views/percorsos/_form.html.erb
<%= form_for(@percorso) do |f| %>
  <% if @percorso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@percorso.errors.count, "error") %> prohibited this percorso from being saved:</h2>

      <ul>
      <% @percorso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend><%= f.label :data %></legend>
    <%= f.date_select('data', start_year: 2017) %>
  </fieldset><br>
  <fieldset>
    <legend><%= f.label :ora %></legend>
    <%= f.time_select :ora %>
  </fieldset><br>
  <fieldset>
    <legend><%= f.label :partenza %></legend>
    <%= f.text_field :partenza %>
  </fieldset><br>
  <fieldset>
    <legend><%= f.label :destinazione %></legend>
    <%= f.text_field :destinazione %>
  </fieldset>
  <li role="separator" class="divider"></li>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/percorsos/_form_photo.html.erb
<%= form_for(@percorso, url: aggiorna_photo_percorso_url, remote: true) do |f| %>
  <div class="row" align="center">
    <%= text_field(:patch, :photo) %>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-6">
      <a class="btn btn-success center-block" id="aggiorna_photo">Invia</a>
    </div>
    <div class="col-xs-6">
      <a class="btn btn-danger center-block" id="cancella_photo">Cancella</a>
    </div>
  </div>
<% end %>

app/views/percorsos/_message_button.html.erb
<div class="row message_div" id="message_button">
  <br>
  <% if @isPartecipante %>
    <% @idDestinatario = "#{current_user.uid}.#{@percorso.utref}" %>
    <a class="btn btn-primary rispondi center-block">Invia messaggio al creatore!</a>
  <% end %>
  <% if current_user && current_user.uid == @percorso.utref  %>
    <% @idDestinatario = 'all' %>
    <a class="btn btn-primary rispondi center-block">Invia messaggio a tutti i partecipanti!</a>
  <% end %>
  <div class="row messageArea" style="display: none;">
    <%= render 'percorsos/message_form' %>
  </div>
</div>

app/views/percorsos/_message_form.html.erb
<%= form_for(@percorso, url: send_message_percorso_url, remote: true) do |f| %>
  <div class="col-xs-12">
    <%= text_area(:message, :text, rows: 2, cols: 32) %>
  </div>
  <%= hidden_field(:destinatario, :id, value: @idDestinatario) %>
  <div class="col-xs-12">
    <div class="row">
      <div class="col-xs-6">
        <a class="btn btn-success center-block message_invia">Invia</a>
      </div>
      <div class="col-xs-6">
        <a class="btn btn-danger center-block message_cancella">Cancella</a>
      </div>
    </div>
  </div>
<% end %>

app/views/percorsos/_messages.html.erb
<div id="messages">
  <br>
  <strong>Messaggi:</strong>
  <br>
  <% if @messages.nil? || @messages.empty? %>
    <p class="text-center">
        Non ci sono aggiornamenti sul percorso!
    </p>
  <% else %>
      <% @messages.each do |message| %>
        <div class="message_div">
          <div class="row">
            <div class="col-xs-3 justify-content-center">
              <div class="row text-center">
                <%= image_tag message[1], alt: message[2], class: 'img-circle  img-responsive center-block' %>
              </div>
              <div class="row text-center">
                <%= message[2] %>
              </div>
            </div>
            <div class="col-xs-9">
              <div class="row">
                <%= message[3] %><br>
              </div>
              <br>
              <% if current_user.uid == @percorso.utref %>
                <div class="row text-right">
                  <a class="btn btn-primary rispondi" style="margin-right:15px;">Rispondi</a>
                </div>
              <% end %>
            </div>
          </div>
          <% if current_user.uid == @percorso.utref %>
            <div class="row messageArea" style="display: none;">
              <% @idDestinatario = message[0] %>
              <%= render 'message_form' %>
            </div>
          <% end %>
        </div>
        <% end %>
    <% end %>
</div>

app/views/percorsos/_partecipanti.html.erb
<strong>Partecipanti</strong><br>
<% @partecipanteInfo.each do |partecipante| %>
  <% if current_user && current_user.uid == partecipante[2] %>
    <div id="yourPartecipa">
  <% else %>
    <div>
  <% end %>
  <% if(!current_user.nil?) %>
    <li class="list-group-item">
      <%= image_tag partecipante[0], alt: partecipante[1], class: 'img-circle' %>
  <% end %>
  <span class="badge" style="margin-top:15px;">
    <%= partecipante[1] %>
  </span>
    </li>
  </div>
<% end %>

app/views/percorsos/edit.html.erb
<div class="container text-center form-div">
  <h2 style="color: #FEFEFE; margin-bottom: 0.4em;">Aggiorna il percorso</h2>
  <%= render 'form' %><br>
  <%= link_to 'Torna indietro', @percorso, class: 'link-form' %>
</div>

app/views/percorsos/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
  <p class="lead text-center"><%= link_to "Crea nuovo percorso", new_percorso_path, class: 'label label-warning' %></p>
<% end %>
<form class="form-inline text-center" action="/percorsos" method="GET" name="ricerca">
  <div class="form-group">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input  type="text" class="form-control" placeholder="Partenza" name="partenza">
    <input  type="text" class="form-control" placeholder="Destinazione" name="destinazione">
    <input  type="date" class="form-control" name="data">
    <input class="btn btn-primary" type="submit" value="Cerca" style="inline-block:float-right;">
  </div>
</form>
<br>
<% if @percorsos.empty? %>
  <div class="well">
    <p class="lead text-center">
      Non ci sono persorsi da mostrare!
    </p>
  </div>
<% else %>
  <section id="percorsi">
  <% @percorsos.each do |percorso| %>
    <figure class="effect-oscar wowload fadeIn animated" style="visibility: visible; animation-name: fadeIn;">
      <% if !percorso.image.nil? %>
        <%= image_tag(percorso.image , :alt => 'foto della città') %>
      <% else %>
        <%= image_tag('8.jpg', :alt => 'foto della città') %>
      <% end %>
      <figcaption>
        <h2><%= percorso.partenza + " - " + percorso.destinazione %></h2>
          <p>Data di partenza: <%= percorso.data %><br>
            <%= link_to "Mostra di più.", percorso_path(percorso) %></p>
      </figcaption>
    </figure>
  <% end %>
</section>
<% end %>

app/views/percorsos/new.html.erb
<div class="container text-center form-div">
  <h2 style="color: #FEFEFE; margin-bottom: 0.4em;">Nuovo percorso</h2>
  <%= render 'form' %><br>
  <%= link_to 'Torna indietro', percorsos_path, class: 'link-form' %>
</div>

app/views/percorsos/show.html.erb
<p id="notice"><%= notice %></p>
<br><br><br>
<div class="container">
  <div id="pagina_percorso" class="row">
  <!--          left          left          left        left      -->
    <div id ="left" class="col-sm-6 col-md-3">
      <div class="col-xs-12">
        <div id ="r-up creatore" class="row">
          <strong>Creatore</strong><br>
          <li class="list-group-item">
            <%= image_tag @fotoC, alt: @utente, class: 'img-circle' %>
            <span class="badge" style="margin-top:15px;">
              <%= @utente %>
            </span>
          </li>
        </div>
        <br>
        <fieldset>
          <legend class="legend_show">Info:</legend>
          <br>
          <div class="row">
            <div class="col-xs-4 col-md-5"><strong>Partenza:</strong></div>
            <div class="col-xs-8 col-md-7"><%= @percorso.partenza.capitalize %></div>
          </div>
          <div class="row">
            <div class="col-xs-4 col-md-5"><strong>Data:</strong></div>
            <div class="col-xs-8 col-md-7"><%= @percorso.data.strftime("%d-%m-%Y") %></div>
          </div>
          <div class="row">
            <div class="col-xs-4 col-md-5"><strong>Ora:</strong></div>
            <div class="col-xs-8 col-md-7"><%= @percorso.ora.hour  %>:<%= @percorso.ora.min  %></div>
          </div>
          <div class="row">
            <div class="col-xs-5 col-md-5"><strong>Destinazione:</strong></div>
            <div class="col-xs-7 col-md-7"><%= @percorso.destinazione.capitalize %></div>
          </div>
          <div class="row">
            <div class="col-xs-4 col-md-5"><strong>Durata:</strong></div>
            <div class="col-xs-8 col-md-7"><%= ((@percorso.durata)/60) %><strong> minuti</strong></div>
          </div>
        </fieldset>
        <br>
        <% if current_user && current_user.uid == @percorso.utref %>
        <div id ="l-dn" class="row lead text-center">
          <div class="col-xs-4">
            <%= link_to 'Aggiorna', edit_percorso_path(@percorso), class: 'link-form' %>
          </div>
          <div class="col-xs-2"></div>
          <div class="col-xs-4">
            <%= link_to 'Cancella', percorso_path(@percorso), method: :delete, data: { confirm: 'Sei sicuro?' }, class: 'link-form' %>
          </div>
        </div>
        <div class="row" align="center">
          <a class="btn btn-success text-center" id="link_photo" >Aggiungi il link della foto</a>
        </div>
        <div class="row" style="display:none;" id="photo_container">
          <%= render 'form_photo' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-6 col-md-9">

<!--        center       center     center      center        center           center  -->
      <div id ="map" class="col-sm-12 col-md-8">
        <ruby>
            <iframe width="520" height="450" frameborder="1" style="border:1"
            src=https://www.google.com/maps/embed/v1/directions?key=AIzaSyBvf51KQC6u-v6nVflhxbD0xbC1PSJEdpM&origin=<%= @percorso.partenza %>+italia&destination=<%= @percorso.destinazione %>+italia></iframe>
        </ruby>
      </div>
<!-- right      right      right      right      right      right      right      -->
      <div id="right" class="col-sm-12 col-md-4">
        <div id ="center-partecipanti" class="row">
          <%= render 'partecipanti' %>
        </div>
        <br>
        <div id="part_canc" class="row">
            <% if(!current_user.nil? && current_user.uid != @percorso.utref && !@isPartecipante )%>
              <%=link_to "Partecipa" , percorso_partecipantis_path(@percorso, :percorso => @percorso, :creator => @percorso.utref),
              method: :post, class: "btn btn-success center-block", id: 'partecipaButton', remote: true %>
            <% end %>

          <% if(@isPartecipante )%>
            <%=link_to "Cancellami" , percorso_partecipanti_path(@percorso, @partecipante, :percorso => @percorso),
            method: :delete, class: "btn btn-danger center-block", id: 'cancellaButton', remote: true %>
          <% end %>
        </div><!--close right div-->
        <div id="message_container" class="row">
          <% if current_user && (@isPartecipante || current_user.uid == @percorso.utref) %>
            <%= render 'messages' %>
          <% end %>
        </div>
        <%= render 'message_button' %>
      </div>
    </div>
  </div>
</div>