config/routes.rb
Rails.application.routes.draw do
  root 'percorsos#index'
  resources :percorsos do
    resources :partecipantis, only: [:create, :destroy]
  end

  get '/auth/google/callback', to:  "sessions#create"

  delete '/logout', to: 'sessions#destroy'

  resources :percorsos do
    patch :send_message, on: :member
    patch :aggiorna_photo, on: :member
  end

end

app/models/partecipanti.rb
class Partecipanti < ActiveRecord::Base
end

app/controllers/partecipantis_controller.rb
require "bunny"
class PartecipantisController < ApplicationController
  before_action :set_partecipanti, only: [:show, :edit, :update, :destroy]

  # GET /partecipantis
  # GET /partecipantis.json
  def index
    @partecipantis = Partecipanti.all
  end

  # GET /partecipantis/1
  # GET /partecipantis/1.json
  def show
  end

  # GET /partecipantis/new
  def new
    @partecipanti = Partecipanti.new
  end

  # GET /partecipantis/1/edit
  def edit
  end

  # POST /partecipantis
  # POST /partecipantis.json
  def create
    id = current_user.uid
    @percorso = Percorso.find(params[:percorso])
    @partecipanti = Partecipanti.new(percorso: @percorso.id, utente:  id)

    respond_to do |format|
      if @partecipanti.save
        conn = Bunny.new
        conn.start
        ch = conn.create_channel
        x = ch.topic("#{@percorso.id}")
        queue = ch.queue("#{@percorso.id}#{id}")
        queue.bind(x, :routing_key => "all")
        queue.bind(x, :routing_key => "#{id}")
        ch.close
        conn.close
        format.html { redirect_to percorso_path(percorso), notice: 'Adesso fai parte di questo percorso!.' }
        format.js {}
        format.json { render :show, status: :created, location: @partecipanti }
      else
        format.html { render :new }
        format.json { render json: @partecipanti.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partecipantis/1
  # PATCH/PUT /partecipantis/1.json
  def update
    respond_to do |format|
      if @partecipanti.update(partecipanti_params)
        format.html { redirect_to @partecipanti, notice: 'Partecipanti was successfully updated.' }
        format.json { render :show, status: :ok, location: @partecipanti }
      else
        format.html { render :edit }
        format.json { render json: @partecipanti.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partecipantis/1
  # DELETE /partecipantis/1.json
  def destroy
    @partecipanti.destroy
    @percorso = Percorso.find(params[:percorso])
    conn = Bunny.new
    conn.start
    ch = conn.create_channel
    queue = ch.queue("#{@percorso.id}#{@partecipanti.utente}")
    queue.delete
    ch.close
    conn.close
    respond_to do |format|
      format.html { redirect_to percorso_path(@percorso.id), notice: 'Adesso non fai più parte di questo percorso.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partecipanti
      @partecipanti = Partecipanti.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partecipanti_params
      params.require(:partecipanti).permit(:percorso, :utente)
    end
end

app/helpers/partecipantis_helper.rb
module PartecipantisHelper
end

app/views/partecipantis/_form.html.erb
<%= form_for(@partecipanti) do |f| %>
  <% if @partecipanti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partecipanti.errors.count, "error") %> prohibited this partecipanti from being saved:</h2>

      <ul>
      <% @partecipanti.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :percorso %><br>
    <%= f.text_field :percorso %>
  </div>
  <div class="field">
    <%= f.label :utente %><br>
    <%= f.text_field :utente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partecipantis/create.js.erb
$('#partecipaButton').fadeOut('slow', function() {
  var a = $('<%=link_to "Cancellami" , percorso_partecipanti_path(@percorso, @partecipanti, :percorso => @percorso.id), method: :delete, class: "btn btn-danger center-block", id: "cancellaButton", remote: true %>').hide();
  $(this).replaceWith(a);
  $('#cancellaButton').fadeIn('slow');
});
var partecipanteDiv = $('<div id="yourPartecipa"><li class="list-group-item"><%= j image_tag current_user.image_url, alt: current_user.name, class: "img-circle" %><span class="badge" style="margin-top:15px;"><%= j current_user.name %></span></li></div>').hide();
$('#center-partecipanti').append(partecipanteDiv);
$('#yourPartecipa').slideDown('slow');
$('#message_container').append('<%= j render "percorsos/messages" %>');
$('#message_button').children(':eq(0)').after('<a class="btn btn-primary rispondi center-block">Invia messaggio al creatore!</a>');
$('#message_button').slideDown();
$('.rispondi').click( function () {
  $(this).slideUp()
  .closest('.message_div')
  .children('.messageArea')
  .slideDown();
});
$('.message_cancella').click( function () {
  $(this).closest('.messageArea')
  .slideUp()
  .closest('.message_div')
  .find('.rispondi')
  .slideDown();
});
$('.message_invia').click( function () {
  $(this).closest('.messageArea')
  .attr('id', 'sending');
});

app/views/partecipantis/destroy.js.erb
$('#cancellaButton').fadeOut('slow', function() {
  var a = $('<%= j link_to "Partecipa", percorso_partecipantis_path(@percorso, :percorso => @percorso.id, :creator => @percorso.utref), method: :post, class: "btn btn-success center-block", id: "partecipaButton", remote: true %>').hide();
  $(this).replaceWith(a);
  $('#partecipaButton').fadeIn('slow');
});
$('#yourPartecipa').slideUp('slow', function () {
  $(this).remove();
});
$('#messages').fadeOut('fast', function () {
  $(this).remove();
});
$('#message_button').children('#messageArea').slideUp();
$('#message_button').slideUp('fast', function () {
  $(this).children('a').remove();
});

app/views/partecipantis/edit.html.erb
<h1>Editing Partecipanti</h1>

<%= render 'form' %>

<%= link_to 'Show', @partecipanti %> |
<%= link_to 'Back', partecipantis_path %>

app/views/partecipantis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Partecipantis</h1>

<table>
  <thead>
    <tr>
      <th>Percorso</th>
      <th>Utente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partecipantis.each do |partecipanti| %>
      <tr>
        <td><%= partecipanti.percorso %></td>
        <td><%= partecipanti.utente %></td>
        <td><%= link_to 'Show', partecipanti %></td>
        <td><%= link_to 'Edit', edit_partecipanti_path(partecipanti) %></td>
        <td><%= link_to 'Destroy', partecipanti, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partecipanti', new_partecipanti_path %>

app/views/partecipantis/new.html.erb
<h1>New Partecipanti</h1>

<%= render 'form' %>

<%= link_to 'Back', partecipantis_path %>

app/views/partecipantis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Percorso:</strong>
  <%= @partecipanti.percorso %>
</p>

<p>
  <strong>Utente:</strong>
  <%= @partecipanti.utente %>
</p>

<%= link_to 'Edit', edit_partecipanti_path(@partecipanti) %> |
<%= link_to 'Back', partecipantis_path %>