config/routes.rb
Rails.application.routes.draw do
  root 'percorsos#index'
  resources :percorsos do
    resources :partecipantis, only: [:create, :destroy]
  end

  get '/auth/google/callback', to:  "sessions#create"

  delete '/logout', to: 'sessions#destroy'

  resources :percorsos do
    patch :send_message, on: :member
    patch :aggiorna_photo, on: :member
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>El Discovery</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>

  <!-- font awesome -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" >
        <div class="container" >
          <div class="navbar-header" >
            <%= link_to image_tag("eldiscovery.jpg"), root_path %>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse" >
            <ul class="nav navbar-nav navbar-right scroll">
              <% if current_user  %>
               <li class=""><%= image_tag current_user.image_url, alt: current_user.name, class: 'img-circle', style: "margin-top:7px;" %></li>
               <li class=""><%= link_to 'Log Out', logout_path, method: :delete, style: "margin-top:5px;" %></li>
              <% else  %>
             <li class=""><%= link_to "Sign in with Google", '/auth/google/', style: "margin-top:5px;" %></li>


              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      <br><br><br>
<%= yield %>

</body>
</html>